import {useEffect,useState} from 'react'
import {useAuth} from '../store/AuthContext'
import {getAllByUserId,getByUserAndDate,putItem,deleteItem,generateId} from '../db'
import type {DailyMeal,MealTemplate} from '../types'
import {toYYYYMMDD,formatPersianDate} from '../lib/utils'
const cats:MealTemplate['category'][]=['صبحانه','میان‌وعده','ناهار','قبل باشگاه','شام']
const raw=[
['صبحانه','اوتمیل موز و دارچین',320,13],['صبحانه','املت تخم‌مرغ و سبزیجات',330,19],['صبحانه','ماست یونانی و گردو',300,22],['صبحانه','تخم‌مرغ آبپز و نان سبوس‌دار',310,20],['صبحانه','پنیر کم‌چرب و گردو و سبزی',340,18],['صبحانه','عدسی با نان سبوس‌دار',360,21],['صبحانه','ماست یونانی و جو دوسر و میوه',320,21],['صبحانه','نیمرو با قارچ و اسفناج',300,19],['صبحانه','پنکیک جو دوسر پروتئینی',340,23],['صبحانه','ساندویچ تخم‌مرغ و سبزیجات',330,21],
['میان‌وعده','سیب و ۱۰ عدد بادام',150,4],['میان‌وعده','ماست یونانی و توت',220,16],['میان‌وعده','پرتقال و ماست کم‌چرب',170,9],['میان‌وعده','دو خرما و ۱۰ بادام',150,3],['میان‌وعده','خیار و هویج با ماست یونانی',120,10],['میان‌وعده','تخم‌مرغ آبپز',100,7],['میان‌وعده','پاپ‌کورن خانگی کم‌روغن',100,3],['میان‌وعده','کیوی و ماست یونانی',150,11],['میان‌وعده','شیر کم‌چرب و دارچین',120,8],['میان‌وعده','پنیر و خیار',110,9],
['ناهار','جوجه و برنج و سالاد',560,45],['ناهار','عدس‌پلو سبک با مرغ',540,34],['ناهار','ماهی و برنج و سالاد',520,40],['ناهار','خوراک مرغ و سبزیجات',430,48],['ناهار','قورمه‌سبزی سبک با برنج',540,35],['ناهار','قیمه سبک با برنج و سالاد',560,34],['ناهار','کباب تابه‌ای کم‌چرب',550,36],['ناهار','خوراک عدس و مرغ',450,43],['ناهار','سالاد مرغ و نان سبوس‌دار',460,47],['ناهار','تن ماهی کم‌روغن و سیب‌زمینی',480,35],
['قبل باشگاه','موز و ماست قبل باشگاه',180,10],['قبل باشگاه','خرما و قهوه قبل تمرین',50,0],['قبل باشگاه','نان و عسل و ماست',190,11],['قبل باشگاه','موز و کره بادام‌زمینی کم',140,4],['قبل باشگاه','سیب و ماست یونانی',150,10],['قبل باشگاه','دو خرما و ماست',180,15],['قبل باشگاه','نان تست و پنیر کم‌چرب',160,9],['قبل باشگاه','موز کوچک و شیر کم‌چرب',180,8],['قبل باشگاه','جو دوسر و ماست',170,12],['قبل باشگاه','خرما و یک لیوان شیر',180,8],
['شام','ماهی و سیب‌زمینی و سبزیجات',480,38],['شام','سالاد مرغ کامل',390,40],['شام','سوپ مرغ و سبزیجات',350,30],['شام','املت سبزیجات و ماست',330,23],['شام','مرغ گریل و سبزیجات',360,46],['شام','ماست یونانی و میوه و مغزها',300,25],['شام','خوراک بوقلمون و سبزیجات',350,45],['شام','تخم‌مرغ و سیب‌زمینی آبپز',360,20],['شام','سالاد تن ماهی سبک',340,32],['شام','سوپ عدس و سبزیجات',330,19],
]
const samples:Omit<MealTemplate,'id'|'userId'|'createdAt'>[]=raw.map(([category,title,calories,protein])=>({category:category as MealTemplate['category'],title:title as string,calories:Number(calories),protein:Number(protein),ingredients:['مواد اولیه متناسب با وعده','سبزیجات تازه','ادویه دلخواه با روغن کم'],instructions:'با روغن کم و حجم متعادل تهیه و مصرف شود.',prepMinutes:10}))
export default function NutritionPage(){
 const{user}=useAuth();const[items,setItems]=useState<MealTemplate[]>([]);const[daily,setDaily]=useState<DailyMeal[]>([]);const[date,setDate]=useState(()=>localStorage.getItem('lifeos-planner-date')||toYYYYMMDD());const[cat,setCat]=useState<MealTemplate['category']>('صبحانه');const[show,setShow]=useState(false);const[form,setForm]=useState({title:'',calories:'',protein:''})
 const load=async()=>{if(!user)return;const[a,b]=await Promise.all([getAllByUserId<MealTemplate>('meal_templates',user.id),getByUserAndDate<DailyMeal>('daily_meals',user.id,date)]);setItems(a);setDaily(b)};useEffect(()=>{load()},[user,date])
 const seed=async()=>{if(!user)return;for(const m of samples)if(!items.some(x=>x.title===m.title&&x.category===m.category))await putItem('meal_templates',{...m,id:generateId(),userId:user.id,createdAt:new Date().toISOString()});load()}
 const choose=async(m:MealTemplate)=>{if(!user||daily.some(x=>x.mealId===m.id))return;await putItem('daily_meals',{id:generateId(),userId:user.id,date,mealId:m.id,category:m.category,completed:false,createdAt:new Date().toISOString()});load()}
 const toggle=async(x:DailyMeal)=>{await putItem('daily_meals',{...x,completed:!x.completed});load()};const add=async()=>{if(!user||!form.title.trim())return;await putItem('meal_templates',{id:generateId(),userId:user.id,title:form.title,category:cat,ingredients:[],instructions:'وعده سفارشی',calories:Number(form.calories)||0,protein:Number(form.protein)||0,createdAt:new Date().toISOString()});setForm({title:'',calories:'',protein:''});setShow(false);load()}
 const selected=daily.map(x=>items.find(m=>m.id===x.mealId)).filter(Boolean) as MealTemplate[];const kcal=selected.reduce((s,m)=>s+(m.calories||0),0);const protein=selected.reduce((s,m)=>s+(m.protein||0),0)
 return <div className="p-4 pt-safe max-w-3xl mx-auto"><h1 className="text-xl font-bold">غذا و کالری</h1><p className="text-sm text-zinc-500 mt-1">برای هر روز غذا را انتخاب و پس از خوردن تیک بزن.</p><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="w-full mt-4 px-3 py-2 rounded-xl border" dir="ltr"/><p className="text-sm text-zinc-500 mt-2">{formatPersianDate(date)}</p><div className="grid grid-cols-2 gap-2 mt-3"><div className="bg-white dark:bg-zinc-800 rounded-2xl p-3"><b>{kcal}</b> کالری</div><div className="bg-white dark:bg-zinc-800 rounded-2xl p-3"><b>{protein}g</b> پروتئین</div></div><button onClick={seed} className="w-full mt-3 py-3 rounded-xl bg-primary-600 text-white">افزودن ۱۰ پیشنهاد برای هر وعده</button><button onClick={()=>setShow(!show)} className="w-full mt-2 py-3 rounded-xl border">+ غذای شخصی</button>{show&&<div className="mt-3 bg-white dark:bg-zinc-800 rounded-2xl p-4 space-y-2"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="نام غذا" className="w-full px-3 py-2 rounded-xl border"/><div className="flex gap-2"><input value={form.calories} onChange={e=>setForm({...form,calories:e.target.value})} placeholder="کالری" className="w-1/2 px-3 py-2 rounded-xl border"/><input value={form.protein} onChange={e=>setForm({...form,protein:e.target.value})} placeholder="پروتئین" className="w-1/2 px-3 py-2 rounded-xl border"/></div><button onClick={add} className="w-full py-2 rounded-xl bg-primary-600 text-white">ذخیره در کتابخانه</button></div>}
 <h2 className="font-bold mt-5 mb-2">وعده‌های این روز</h2>{daily.map(x=>{const m=items.find(i=>i.id===x.mealId);return m&&<div key={x.id} className="bg-white dark:bg-zinc-800 rounded-2xl p-3 mb-2 flex items-center gap-3"><button onClick={()=>toggle(x)} className={`w-7 h-7 rounded-full border-2 ${x.completed?'bg-primary-600 border-primary-600 text-white':'border-zinc-300'}`}>{x.completed?'✓':''}</button><div className="flex-1"><b className={x.completed?'line-through text-zinc-400':''}>{m.title}</b><p className="text-xs text-zinc-500">{m.category} · {m.calories||0} کالری</p></div><button onClick={async()=>{await deleteItem('daily_meals',x.id);load()}} className="text-red-500 text-xs">حذف</button></div>})}
 <div className="flex gap-2 overflow-x-auto no-scrollbar my-5">{cats.map(x=><button key={x} onClick={()=>setCat(x)} className={`px-4 py-2 rounded-full whitespace-nowrap ${cat===x?'bg-primary-600 text-white':'bg-zinc-100 dark:bg-zinc-800'}`}>{x}</button>)}</div><div className="space-y-2">{items.filter(x=>x.category===cat).map(m=><div key={m.id} className="bg-white dark:bg-zinc-800 rounded-2xl p-3 flex items-center gap-3"><div className="flex-1"><b>{m.title}</b><p className="text-xs text-zinc-500">{m.calories||0} کالری · {m.protein||0}g پروتئین</p></div><button onClick={()=>choose(m)} className="text-primary-600 text-sm font-bold">+ انتخاب</button></div>)}</div></div>
}
