import {useEffect,useState} from 'react'
import {useAuth} from '../store/AuthContext'
import {getByUserAndDate,getAllByUserId,putItem,deleteItem,generateId} from '../db'
import type {Task,TaskCategory,TaskTemplate} from '../types'
import {toYYYYMMDD,formatPersianDate} from '../lib/utils'
const cats:TaskCategory[]=['سلامت','ورزش','تغذیه','مطالعه','کار','خانه','مراقبت شخصی','دارو','خواب','سایر']
export default function PlannerPage(){const{user}=useAuth();const [date,setDate]=useState(toYYYYMMDD());const[tasks,setTasks]=useState<Task[]>([]);const[templates,setTemplates]=useState<TaskTemplate[]>([]);const[title,setTitle]=useState('');const[category,setCategory]=useState<TaskCategory>('کار');const[time,setTime]=useState('');const[show,setShow]=useState(false)
const load=async()=>{if(!user)return;const[a,b]=await Promise.all([getByUserAndDate<Task>('tasks',user.id,date),getAllByUserId<TaskTemplate>('task_templates',user.id)]);setTasks(a.sort((x,y)=>(x.startTime||'99:99').localeCompare(y.startTime||'99:99')));setTemplates(b)};useEffect(()=>{load()},[user,date])
const add=async()=>{if(!user||!title.trim())return;await putItem('tasks',{id:generateId(),userId:user.id,title:title.trim(),category,date,startTime:time||undefined,priority:'medium',completed:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});setTitle('');setTime('');setShow(false);load()}
const addTemplate=async(t:TaskTemplate)=>{if(!user)return;await putItem('tasks',{id:generateId(),userId:user.id,title:t.title,category:t.category,date,startTime:t.startTime,endTime:t.endTime,priority:t.priority,notes:t.notes,reminder:t.reminder,completed:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});load()}
const toggle=async(t:Task)=>{await putItem('tasks',{...t,completed:!t.completed,completedAt:!t.completed?new Date().toISOString():undefined,updatedAt:new Date().toISOString()});load()}
return <div className="p-4 pt-safe max-w-2xl mx-auto"><h1 className="text-xl font-bold">برنامه‌ریز زندگی</h1><p className="text-sm text-zinc-500 mt-1">هر تاریخ را انتخاب کن و برنامه‌اش را از کتابخانه بساز.</p><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="w-full px-3 py-2 rounded-xl border mt-4" dir="ltr"/><p className="text-sm text-zinc-500 my-3">{formatPersianDate(date)}</p><button onClick={()=>setShow(!show)} className="w-full py-3 rounded-xl bg-primary-600 text-white">+ کار جدید</button>{show&&<div className="bg-white dark:bg-zinc-800 rounded-2xl p-4 mt-3 space-y-3"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="عنوان کار" className="w-full px-3 py-2 rounded-xl border"/><select value={category} onChange={e=>setCategory(e.target.value as TaskCategory)} className="w-full px-3 py-2 rounded-xl border">{cats.map(c=><option key={c}>{c}</option>)}</select><input type="time" value={time} onChange={e=>setTime(e.target.value)} className="w-full px-3 py-2 rounded-xl border"/><button onClick={add} className="w-full py-2 rounded-xl bg-primary-600 text-white">ذخیره در این روز</button></div>}
{templates.length>0&&<section className="mt-5"><h2 className="font-bold mb-2">انتخاب از کارهای ذخیره‌شده</h2><div className="flex gap-2 overflow-x-auto no-scrollbar pb-2">{templates.map(t=><button key={t.id} onClick={()=>addTemplate(t)} className="flex-shrink-0 text-right p-3 rounded-xl bg-primary-50 dark:bg-primary-900/30 text-sm"><b>{t.title}</b><div className="text-xs text-zinc-500">{t.category}{t.startTime&&` · ${t.startTime}`}</div></button>)}</div></section>}
<section className="mt-5"><h2 className="font-bold mb-2">برنامه این روز ({tasks.length})</h2><div className="space-y-2">{tasks.map(t=><div key={t.id} className="bg-white dark:bg-zinc-800 p-4 rounded-2xl flex gap-3 items-center"><button onClick={()=>toggle(t)} className={`w-7 h-7 rounded-full border-2 flex items-center justify-center ${t.completed?'bg-primary-600 border-primary-600 text-white':'border-zinc-300'}`}>{t.completed?'✓':''}</button><div className="flex-1"><p className={t.completed?'line-through text-zinc-400':'font-medium'}>{t.title}</p><p className="text-xs text-zinc-500">{t.category}{t.startTime&&` · ${t.startTime}`}</p></div><button onClick={async()=>{await deleteItem('tasks',t.id);load()}} className="text-red-500 text-xs">حذف</button></div>)}{!tasks.length&&<p className="text-center text-zinc-400 py-8">برای این روز برنامه‌ای نیست.</p>}</div></section></div>}
